name: Docs issue report
description: Describe this issue template's purpose here.
title: "[docs] <title>"
labels: ["documentation"]
assignees:
  - Qualyyy
body:
  - type: textarea
    attributes:
      label: What part of the documentation needs improvement?
      description: A clear and concise description of what documentation is unclear, missing, or needs to be updated.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current documentation
      description: Link to or quote the documentation that needs improvement.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested improvement
      description: A clear and concise description of how the documentation should be improved or what should be added.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the documentation issue here.
    validations:
      required: false
